# Generated by Django 4.1.5 on 2023-01-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zomato", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionManagement",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("session_token", models.CharField(max_length=45)),
                ("token_expiry", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "session_management",
                "managed": False,
            },
        ),
    ]
